FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    libatlas-base-dev \
    liblapack-dev \
    libblas-dev \
    python3-dev \
    && apt-get clean

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Download NLTK data at build time
RUN python -m nltk.downloader stopwords wordnet punkt

# Command to run your app
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8000"]